name: CI and Release

# semantic releases , typecheks, linting and tests on main branch.

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: run typecheck
        run: bun typecheck
      - name: run lint
        run: bun lint:check
      - name: Run tests
        run: bun test

      - name: Semantic Release
        run: bunx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
